#!/usr/bin/env python3
"""
Nextraプロジェクトセットアップスクリプト

Nextra静的サイトジェネレーターのプロジェクト構造を初期化します。

使用方法:
    python scripts/setup_nextra.py --output reports/nextra-site --title "My Report"

機能:
    - package.json生成
    - next.config.js生成
    - theme.config.tsx生成
    - tsconfig.json生成
    - ディレクトリ構造作成
    - .gitignore追加
"""

import argparse
import json
import subprocess
from pathlib import Path


def create_package_json(nextra_dir: Path, title: str):
    """package.jsonを生成"""
    package_json = {
        "name": "refactoring-report",
        "version": "1.0.0",
        "private": True,
        "scripts": {
            "dev": "next dev",
            "build": "next build",
            "start": "next start",
            "export": "next build"
        },
        "dependencies": {
            "next": "^14.2.0",
            "nextra": "^3.0.0",
            "nextra-theme-docs": "^3.0.0",
            "react": "^18.3.0",
            "react-dom": "^18.3.0",
            "d3": "^7.9.0",
            "react-syntax-highlighter": "^15.5.0"
        },
        "devDependencies": {
            "@types/node": "^20.0.0",
            "@types/react": "^18.3.0",
            "@types/d3": "^7.4.0",
            "@types/react-syntax-highlighter": "^15.5.11",
            "typescript": "^5.4.0"
        }
    }

    with open(nextra_dir / "package.json", "w", encoding="utf-8") as f:
        json.dump(package_json, f, indent=2)

    print("✓ package.json created")


def create_next_config(nextra_dir: Path):
    """next.config.jsを生成"""
    config = """const withNextra = require('nextra')({
  theme: 'nextra-theme-docs',
  themeConfig: './theme.config.tsx',
  defaultShowCopyCode: true,
  flexsearch: {
    codeblocks: true
  }
})

module.exports = withNextra({
  output: 'export',  // 静的エクスポート
  images: {
    unoptimized: true
  },
  basePath: '',
  trailingSlash: true,
  reactStrictMode: true
})
"""

    with open(nextra_dir / "next.config.js", "w", encoding="utf-8") as f:
        f.write(config)

    print("✓ next.config.js created")


def create_theme_config(nextra_dir: Path, title: str):
    """theme.config.tsxを生成"""
    # タイトルをコンテキスト別にエスケープ
    title_jsx = title.replace('&', '&amp;').replace('<', '&lt;').replace('>', '&gt;')
    title_js = title.replace('\\', '\\\\').replace("'", "\\'")
    title_attr = title.replace('&', '&amp;').replace('"', '&quot;').replace('<', '&lt;').replace('>', '&gt;')
    config = f"""import {{ DocsThemeConfig }} from 'nextra-theme-docs'

const config: DocsThemeConfig = {{
  logo: <span style={{{{ fontWeight: 'bold', fontSize: '1.2rem' }}}}>{title_jsx}</span>,
  project: {{
    link: 'https://github.com/anthropics/claude-code'
  }},
  docsRepositoryBase: 'https://github.com/anthropics/claude-code/tree/main/reports',
  footer: {{
    text: (
      <span>
        Generated by{' '}
        <a href="https://claude.ai/code" target="_blank" rel="noopener">
          Claude Code Refactoring Agent
        </a>
      </span>
    )
  }},
  sidebar: {{
    defaultMenuCollapseLevel: 1,
    toggleButton: true
  }},
  toc: {{
    backToTop: true,
    title: 'On This Page'
  }},
  search: {{
    placeholder: 'Search documentation...'
  }},
  darkMode: true,
  nextThemes: {{
    defaultTheme: 'system'
  }},
  useNextSeoProps() {{
    return {{
      titleTemplate: '%s – {title_js}'
    }}
  }},
  head: (
    <>
      <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      <meta property="og:title" content="{title_attr}" />
      <meta property="og:description" content="System refactoring analysis and design documentation" />
    </>
  )
}}

export default config
"""

    with open(nextra_dir / "theme.config.tsx", "w", encoding="utf-8") as f:
        f.write(config)

    print("✓ theme.config.tsx created")


def create_tsconfig(nextra_dir: Path):
    """tsconfig.jsonを生成"""
    tsconfig = {
        "compilerOptions": {
            "target": "ES2020",
            "lib": ["ES2020", "DOM", "DOM.Iterable"],
            "jsx": "preserve",
            "module": "ESNext",
            "moduleResolution": "bundler",
            "resolveJsonModule": True,
            "allowJs": True,
            "strict": True,
            "noEmit": True,
            "esModuleInterop": True,
            "skipLibCheck": True,
            "forceConsistentCasingInFileNames": True,
            "incremental": True,
            "paths": {
                "@/*": ["./*"]
            }
        },
        "include": ["next-env.d.ts", "**/*.ts", "**/*.tsx"],
        "exclude": ["node_modules", "out", ".next"]
    }

    with open(nextra_dir / "tsconfig.json", "w", encoding="utf-8") as f:
        json.dump(tsconfig, f, indent=2)

    print("✓ tsconfig.json created")


def create_gitignore(nextra_dir: Path):
    """.gitignoreを生成"""
    gitignore = """# Dependencies
node_modules/
package-lock.json
yarn.lock

# Next.js
.next/
out/

# TypeScript
*.tsbuildinfo

# Logs
*.log
npm-debug.log*

# OS
.DS_Store
Thumbs.db

# IDE
.vscode/
.idea/
"""

    with open(nextra_dir / ".gitignore", "w", encoding="utf-8") as f:
        f.write(gitignore)

    print("✓ .gitignore created")


def create_directory_structure(nextra_dir: Path):
    """ディレクトリ構造を作成"""
    dirs = [
        nextra_dir / "pages",
        nextra_dir / "components",
        nextra_dir / "public",
        nextra_dir / "public" / "data",
        nextra_dir / "styles"
    ]

    for dir_path in dirs:
        dir_path.mkdir(parents=True, exist_ok=True)

    print("✓ Directory structure created")


def create_index_page(nextra_dir: Path, title: str):
    """トップページを生成"""
    index_content = f"""# {title}

Welcome to the system refactoring analysis and design documentation.

## Overview

This documentation contains:

- **Executive Summary** - High-level overview and key findings
- **System Analysis** - Ubiquitous language, actors, roles, and domain mapping
- **Quality Evaluation** - MMI and DDD evaluation results
- **Architecture Design** - DDD redesign, microservices architecture, API design
- **Domain Stories** - Domain storytelling and scenarios
- **Cost Estimates** - Infrastructure and operational cost estimates
- **Implementation Specs** - Detailed implementation specifications
- **Test Specifications** - Unit, integration, and E2E test specifications
- **Knowledge Graph** - Interactive knowledge graph visualization

## Getting Started

Navigate through the sidebar to explore each section.

Use the search bar (Ctrl+K or ⌘K) to quickly find specific topics.

---

*Generated by [Claude Code](https://claude.ai/code) on {{{{ new Date().toISOString().split('T')[0] }}}}*
"""

    with open(nextra_dir / "pages" / "index.mdx", "w", encoding="utf-8") as f:
        f.write(index_content)

    print("✓ index.mdx created")


def create_root_meta(nextra_dir: Path):
    """ルートレベルの_meta.jsonを生成"""
    meta = {
        "index": {
            "title": "Overview",
            "type": "page"
        },
        "00_summary": "Executive Summary",
        "01_analysis": "System Analysis",
        "02_evaluation": "Quality Evaluation",
        "03_design": "Architecture Design",
        "04_stories": "Domain Stories",
        "05_estimate": "Cost Estimates",
        "06_implementation": "Implementation Specs",
        "07_test-specs": "Test Specifications",
        "graph": "Knowledge Graph"
    }

    with open(nextra_dir / "pages" / "_meta.json", "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)

    print("✓ _meta.json created")


def create_global_css(nextra_dir: Path):
    """グローバルCSSを生成"""
    css = """/* Custom global styles */

.graph-viewer {
  width: 100%;
  height: 600px;
  border: 1px solid var(--nx-border-color);
  border-radius: 8px;
  overflow: hidden;
  margin: 2rem 0;
}

.config-file {
  margin: 2rem 0;
}

/* Mermaid diagram container */
.mermaid {
  display: flex;
  justify-content: center;
  margin: 2rem 0;
  padding: 1rem;
  background: var(--nx-bg-secondary);
  border-radius: 8px;
}

/* Custom table styles */
table {
  width: 100%;
  margin: 2rem 0;
  border-collapse: collapse;
}

table th {
  background: var(--nx-bg-secondary);
  font-weight: 600;
  text-align: left;
  padding: 0.75rem 1rem;
}

table td {
  padding: 0.75rem 1rem;
  border-bottom: 1px solid var(--nx-border-color);
}

/* Print styles */
@media print {
  .nextra-sidebar-container {
    display: none;
  }

  .nextra-nav-container {
    display: none;
  }

  main {
    max-width: 100% !important;
  }
}
"""

    with open(nextra_dir / "styles" / "globals.css", "w", encoding="utf-8") as f:
        f.write(css)

    print("✓ globals.css created")


def install_dependencies(nextra_dir: Path, skip_install: bool):
    """npm依存関係をインストール"""
    if skip_install:
        print("⚠ Skipping npm install (--skip-install)")
        return

    print("Installing npm dependencies...")
    try:
        subprocess.run(
            ["npm", "install"],
            cwd=nextra_dir,
            check=True,
            capture_output=True,
            text=True
        )
        print("✓ npm dependencies installed")
    except subprocess.CalledProcessError as e:
        print(f"✗ npm install failed: {e.stderr}")
        print("You can manually install later with: cd {} && npm install".format(nextra_dir))


def setup_nextra(output_dir: str, title: str, skip_install: bool):
    """Nextraプロジェクトをセットアップ"""
    nextra_dir = Path(output_dir)

    print(f"Setting up Nextra project at: {nextra_dir}")

    # Create directory
    nextra_dir.mkdir(parents=True, exist_ok=True)

    # Generate config files
    create_package_json(nextra_dir, title)
    create_next_config(nextra_dir)
    create_theme_config(nextra_dir, title)
    create_tsconfig(nextra_dir)
    create_gitignore(nextra_dir)

    # Create directory structure
    create_directory_structure(nextra_dir)

    # Create initial pages
    create_index_page(nextra_dir, title)
    create_root_meta(nextra_dir)

    # Create styles
    create_global_css(nextra_dir)

    # Install dependencies
    install_dependencies(nextra_dir, skip_install)

    print(f"\n✅ Nextra project setup complete!")
    print(f"\nNext steps:")
    print(f"  1. cd {nextra_dir}")
    print(f"  2. npm run dev  # Start development server")
    print(f"  3. npm run build  # Build for production")


def main():
    parser = argparse.ArgumentParser(description="Setup Nextra project for report compilation")
    parser.add_argument(
        "--output",
        type=str,
        default="reports/nextra-site",
        help="Output directory for Nextra project (default: reports/nextra-site)"
    )
    parser.add_argument(
        "--title",
        type=str,
        default="Refactoring Analysis Report",
        help="Report title (default: Refactoring Analysis Report)"
    )
    parser.add_argument(
        "--skip-install",
        action="store_true",
        help="Skip npm install (useful for CI/CD)"
    )

    args = parser.parse_args()

    setup_nextra(args.output, args.title, args.skip_install)


if __name__ == "__main__":
    main()
